name: Artillery GHA Test

on:
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  artillery:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create dotenv file
        env:
          SECRET_URL: ${{ secrets.SECRET_URL }}
        run: |
          echo "SECRET_URL=$SECRET_URL" >> .env

      - name: Execute load tests
        uses: artilleryio/action-cli@v1
        with:
          command: run test.yml --dotenv .env
